name: Production CI/CD Pipeline for Events

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_prod_environment:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir pandas pytest

  run_smoke_test:
    needs: build_prod_environment
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python environment again
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Run smoke tests
      - name: Run smoke tests
        run: |
          python -m pytest tests/test_events_prod.py

  deploy_to_production:
    needs: run_smoke_test
    runs-on: ubuntu-latest
    if: success()
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Deploy to production
      - name: Deploy program to prod
        run: |
          echo "Deploying application to production environment..."
          # For now we'll just simulate this step because we aren't deploying to Azure, AWS etc --- :)
          echo ">>> [SUCCESS] - Deployment completed successfully."
