name: Staging CI/CD Pipeline for Events

on:
  push:
    branches:
      - staging
      
permissions:
  contents: write
  pull-requests: write


  
jobs:
  build_staging_environment:
    runs-on: ubuntu-latest
    steps:
      
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir pandas pytest
          python -m pip list

  run_staging_tests:
    needs: build_staging_environment
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code again for the test job
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python environment again
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Install dependencies again
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir pandas pytest

      # 4. Set PYTHONPATH to include the src directory
      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src

      # 5. Print Python Path
      - name: Print Python Path
        run: |
          which python
          python --version
          pip --version

      # 6. Run end-to-end and performance tests
      - name: Run end-to-end and performance tests
        run: |
          python -m pytest tests/test_events_staging.py


  create_pr_to_production:
    needs: run_staging_tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Authenticate GitHub CLI with PAT
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      # 3. Create a pull request to the main branch
      - name: Create pull request to Production
        run: |
          gh pr create -B main -H staging --title "Deploy changes from STAGING to PRODUCTION" --body "This PR is created by GitHub Actions for manual review."
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
